local opt = vim.opt
opt.number = true
opt.relativenumber = true
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.autoindent = true
opt.mouse = "a"
opt.clipboard = "unnamedplus"
opt.scrolloff = 5
opt.termguicolors = true
